config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, skip: [:registrations]

  root "pages#home"

  resources :users do
    resources :bike_services
    member do
      get :services_pdf
    end
  end

  get "up" => "rails/health#show", as: :rails_health_check

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,:recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bike_service.rb
class BikeService < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :bike_services, dependent: :destroy

  validates :nombre, :apellido, presence: true
  validates :email, uniqueness: true, presence: true
  validates :telefono, format: { with: /\A(\+34|0034|34)?[6789]\d{8}\z/, message: "no es un número de teléfono válido" }


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bike_services_controller.rb
class BikeServicesController < ApplicationController
  before_action :set_bike_service, only: %i[ show destroy ]


  def index
    @user = User.find(params[:user_id])
    @bike_services = @user.bike_services
  end


  def show
  end


  def new
    @user = User.find(params[:user_id])
    @bike_service = @user.bike_services.build
  end


  def create
    @user = User.find(params[:user_id])
    @bike_service = @user.bike_services.build(bike_service_params)
    if @bike_service.save
      redirect_to @user, notice: 'Servicio de bicicleta creado exitosamente.'
    else
      render :new
    end
  end

  def destroy
    if @bike_service.destroy
      redirect_to user_path(@user), status: :see_other, notice: "Servicio eliminado exitosamente."
    else
      redirect_to user_path(@user), alert: "No se pudo eliminar el servicio."
    end
  end


  private

    def set_bike_service
      @user = User.find(params[:user_id])
      @bike_service = @user.bike_services.find(params[:id])
    end


    def bike_service_params
      params.require(:bike_service).permit(:user_id, :descripcion, :date, :cost)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :authenticate_admin!
  def home
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  before_action :set_user, only: %i[ show edit update destroy services_pdf ]

  def index
    @users = User.includes(:bike_services)
  end

  def show
    @user_services = @user.bike_services.order(date: :desc)
    @total_price_services = @user_services.sum(:cost)
  end

  def new
    @user = User.new
  end

  def edit
  end

  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: "Usuario creado" }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: "Usuario actualizado" }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def services_pdf

    @bike_services = @user.bike_services.order(date: :desc)

    respond_to do |format|
      format.pdf do
        pdf = ServicePdf.new(@user, @bike_services)
        send_data pdf.render,
          filename: "servicios_#{@user.nombre}_#{Date.today}.pdf",
          type: "application/pdf",
          disposition: "inline"
      end
    end

  end
  def destroy
    if @user.destroy
      redirect_to users_path, status: :see_other, notice: "Usuario eliminado"
    else
      redirect_to users_path, alert: "No se pudo eliminar el usuario."
    end
  end

  private
    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:nombre, :apellido, :telefono, :email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bike_services_helper.rb
module BikeServicesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admins/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />
  <% end %>
<% end %>

app/views/bike_services/_form.html.erb
<div class="mx-auto mt-3 w-50">
  <div class="p-5 rounded bg-light shadow">

    <% if @bike_service.errors.any? %>
      <div class="alert alert-danger">
        <h4>Errores al guardar el servicio:</h4>
        <ul>
          <% @bike_service.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <%= form_with(model: [@user, @bike_service], local: true) do |form| %>

      <div class="mb-3">
        <%= form.label :descripcion, "Descripción", class: "form-label" %>
        <%= form.text_area :descripcion, class: "form-control", rows: 4 %>
      </div>

      <div class="mb-3">
        <%= form.label :date, "Fecha del servicio", class: "form-label" %>
        <%= form.text_field :date, class: "form-control", data: { controller: "datepicker" }, placeholder: "Fecha" %>
      </div>

      <div class="form-floating mb-3">
        <%= form.number_field :cost, class: "form-control", step: "0.01", placeholder: "Precio"  %>
        <%= form.label :cost, "Precio" %>
      </div>

      <div class="d-flex justify-content-between mt-4">
        <%= link_to "← Volver", user, class:"btn btn-outline-secondary" %>
        <%= form.submit "Guardar Servicio", class: "btn btn-primary" %>
      </div>
    <% end %>

  </div>
</div>

app/views/bike_services/index.html.erb
<div class="d-flex flex-column justify-content-center p-3 ">

  <h1 class="text-center mb-5">Reparaciones:</h1>
  <%= link_to "Volver al usuario", user_path(@user), class:"btn btn-sm btn-outline-success mb-2 w-25"  %>


</div>

<div>

  <% if @bike_services.any? %>
    <div class="bike-service-card">
      <% @bike_services.each do |bike_service| %>
        <%= render bike_service %>
      <% end %>

    </div>

  <% else %>

    <p>Este usuario no tiene servicios registrados</p>
    <%= link_to "Volver al usuario", user_path(@user), class:"btn btn-sm btn-outline-success mb-2"  %>

  <% end %>
</div>

app/views/bike_services/new.html.erb
<h1 class="text-center mb-3">Crear Servicio</h1>

<%= render "form", bike_service: @bike_service , user: @user %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bikesec</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= favicon_link_tag 'bici-logo2.png', type: 'image/png' %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "https://cdn.jsdelivr.net/npm/flatpickr/dist/themes/confetti.css", media: "all" %>
    <link href="https://unpkg.com/aos@2.3.1/dist/aos.css" rel="stylesheet">

    <%= javascript_importmap_tags %>

  </head>

  <body>

    <div class="logo">
      <%= link_to users_path do %>
        <%= image_tag "bikesec-logo1.png", alt: "logo1" %>
      <% end %>
    </div>

    <%= yield %>






    <%= turbo_include_tags %>
    <script src="https://unpkg.com/aos@next/dist/aos.js"></script>
    <script>
      AOS.init({
        startEvent: 'DOMContentLoaded'
      });
    </script>
  </body>
</html>

app/views/pages/home.html.erb
<div class="home">

  <p class="p">Gestión de bicicletas y servicios</p>
  <%= link_to "Ver todos clientes", users_path, class: "btn btn-outline-success " %>

</div>

app/views/users/_form.html.erb
<div class="mx-auto mt-4 w-50">
  <%= form_with(model: user, class: "needs-validation p-5 rounded bg-light shadow ") do |form| %>
    <div class="form-floating mb-3" >
      <%= form.text_field :nombre, class: "form-control", placeholder: "Nombre" %>
      <%= form.label :nombre %>
    </div>

    <div class="form-floating mb-3" >
      <%= form.text_field :apellido, class: "form-control", placeholder: "Apellido" %>
      <%= form.label :apellido %>
    </div>

    <div class="form-floating mb-3" >
      <%= form.telephone_field :telefono, class: "form-control", placeholder: "Teléfono" %>
      <%= form.label :telefono %>
    </div>

    <div class="form-floating mb-3" >
      <%= form.email_field :email, class: "form-control", placeholder: "Email" %>
      <%= form.label :email %>
    </div>

    <div>
      <%= link_to "← Volver", user, class:"btn btn-outline-secondary mt-2" %>
      <%= form.submit "Guardar", class: "btn btn-outline-primary mt-2" %>
    </div>
  <% end %>

</div>

app/views/users/_user.html.erb
<div class="card">

  <div class="card-body">

    <h5 class="card-title"><%= user.nombre %> <%= user.apellido %></h5>
    <p>
      <strong>Telefono:</strong>
      <%= user.telefono %>
    </p>

    <p>
      <strong>Email:</strong>
      <%= user.email %>
    </p>

    <div class="users-index-links">
      <%= link_to "Mostrar usuario", user, class:"btn btn-sm btn-outline-success" %>
      <%= link_to "Borrar cliente", user_path(user), method: :delete, data: { confirm: "¿Estás seguro que quieres borrar este cliente?" }, class: "btn btn-sm btn-outline-danger" %>
    </div>

  </div>

</div>

app/views/users/edit.html.erb
<h1 class="text-center mb-3">Editar cliente</h1>

<%= render "form", user: @user %>

app/views/users/index.html.erb
<div class="d-flex flex-column justify-content-center align-items-center mb-5">
  <h2 class="text-center mb-5">Listado de clientes</h2>

  <%= link_to "Crear cliente", new_user_path, class:"btn btn-outline-success w-25 text-center btn-sm" %>
  <%= button_to "Cerrar sesión", destroy_admin_session_path, method: :delete, data: { confirm: "¿Estás seguro?" }, class: "btn btn-sm btn-outline-danger mt-2" %>
</div>
<div data-aos="fade-down" data-aos-easing="linear" data-aos-duration="300" class="user-list">
  <% @users.each do |user| %>
    <%= render user %>
  <% end %>
</div>

app/views/users/new.html.erb
<h3 class="text-center mt-5">Agregar datos del cliente</h3>

<%= render "form", user: @user %>

app/views/users/show.html.erb
<div class="user-show-header">

  <h1 class="text-center">Ficha cliente</h1>

</div>

<div class="user-card">
  <div class="user-card-info">
    <h5 class="text-center mb-3 p-2 border w-50">Informacion del cliente:</h5>

    <p>
      <strong>Nombre:</strong>
      <%= @user.nombre %>
    </p>

    <p>
      <strong>Apellido:</strong>
      <%= @user.apellido %>
    </p>

    <p>
      <strong>Telefono:</strong>
      <%= @user.telefono %>
    </p>

    <p>
      <strong>Email:</strong>
      <%= @user.email %>
    </p>
    <div class="d-flex flex-column justify-content-center text-center">
      <p>
        <strong class="fs-5">Total a pagar: <%= @total_price_services %>€ <strong>
      </p>
      <%= link_to "Generar PDF", services_pdf_user_path(@user, format: :pdf), target: "_blank", class: "btn btn-sm btn-outline-secondary mt-1" %>
    </div>

    <div class="d-flex gap-2 mt-3">
      <%= link_to "Editar cliente", edit_user_path(@user), class: "btn btn-sm btn-outline-success" %>
      <%= link_to "Nuevo servicio", new_user_bike_service_path(@user), class: "btn btn-sm btn-outline-success" %>

    </div>
  </div>


  <div class="user-bike-services-list">
    <h5 class="text-center mb-3 p-2 border w-50">Servicios:</h5>
    <% @user_services.each do |service| %>
      <div class="user-bike-services-item">

        <div class="user-bike-services-info">

          <p class="mb-1 mt-1">Descripción: <%= service.descripcion %></p>
          <p class="mb-1">Fecha: <%= service.date.strftime("%d/%m/%Y") %></p>
          <p class="mb-1">Precio: <%= number_to_currency(service.cost, unit: "€") %></p>

        </div>

        <div class="user-bike-services-links">

          <%= link_to "Borrar", user_bike_service_path(service.user, service), method: :delete, data: { confirm: "¿Estás seguro que quieres borrar este servicio?" }, class: "btn btn-outline-danger" %>

        </div>


      </div>

    <% end %>
  </div>
</div>